safe: false
port: 9005
base-url:    /

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag

source:      ./source/site
destination: ./.publish
plugins_dir: ./source/site/_plugins

future:      true
lsi:         false
highlighter: true
markdown:    kramdown
permalink:   blog/:title

rdiscount:
  extensions: []

# Kramdown
kramdown:
  input: GFM
  hard_wrap: false
  parse_block_html: true
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    line_numbers: false

collections:
  projects:
    label: projects
    output: true
    relative_directory: portfolio/:slug
    directory: portfolio/:slug

  portfolio:
    label: portfolio
    output: true
    relative_directory: portfolio/:slug
    directory: portfolio/:slug

  misc:
    label: misc
    output: true
    relative_directory: portfolio/:slug
    directory: portfolio/:slug


exclude: [
  README.md,
  CHANGELOG.md
]

# Custom vars
current_version:  4.1.0
repo: https://github.com/underlost/underlost.net
site: https://underlost.net/
url: https://underlost.net
author: Tyler Rilling
description: Python Hacker & Pixel Pusher.

blog: /blog/
blog_title: Underlost
blog_deck: By Tyler Rilling
