safe: false
port: 4000
base-url:    /

source:      ./source
destination: ./_site
plugins:     ./source/_plugins

future:      true
lsi:         false
pygments:    true
markdown:    kramdown
permalink:   :title

rdiscount:
  extensions: []

kramdown:
  auto_ids: true,
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  use_coderay: false
  input: GFM

  coderay:
    coderay_wrap: div
    coderay_line_numbers: inline
    coderay_line_numbers_start: 1
    coderay_tab_width: 4
    coderay_bold_every: 10
    coderay_css: style

exclude: [
    "dist",
    "grunt",
    Gemfile,
    Gemfile.lock,
    Procfile,
    gruntfile.js,
    package.json,
    composer.json
]

# Custom vars
current_version:  1.1.0
repo: https://github.com/underlost/underlost.net
site: http://underlost.net/
author: Tyler Rilling

blog: /blog/
blog_title: underlost.net
blog_deck: By Tyler Rilling
